### ISSUE TITLE
Compile error in users.schema.ts

### ISSUE THREAD

**Issue by xiaojin9712** [BretCameron/typescript-mongodb#3]
Hi Bret,

First of all, thanks for your article about how to set up a typescript and MongoDB environment. It was very detailed and I have learned a lot. But there is a problem that has been bothering me for a while. I tried to pull your code and it didn't work as well.

![image](https://user-images.githubusercontent.com/52311332/106911779-7cd60980-673d-11eb-97fa-8f0d9aa0a794.png)

and the error message is:
`Type '(this: IUserModel, min?: number, max?: number) => Promise<IUserDocument[]>' is not assignable to type '(this: Model<Document<any>>, ...args: any[]) => any'.
  The 'this' types of each signature are incompatible.
    Type 'Model<Document<any>>' is not assignable to type 'IUserModel'.ts(2322)`

I double-checked the inheritance chain of interface definition, but I still couldn't solve it because I didn't know much about typescript.

cheers

**Comment by hansbeld** [comment]
running into the same problem. If I add a method definition to the IUserDocument interface it will throw the same error.

**Comment by xiaojin9712** [comment]
my solution is to add type assertions, which, although it doesn't look very elegant, should solve the current problem for now. I'm still learning and I'll let you know if I have any updates.

`UserSchema.statics.findOneOrCreate = <any>findOneOrCreate;
UserSchema.statics.findByAge = <any>findByAge;`

**Comment by xiaojin9712** [comment]
> running into the same problem. If I add a method definition to the IUserDocument interface it will throw the same error.

UPDATE.
it seems the inheritance chain needs to be changed to fit the same shape of UserScheme. A more elegant way to solve this problem could be:
`
- export interface IUserModel extends Model<IUserDocument>
+ export interface IUserModel extends Model<Document<IUserDocument>> {
    findOneOrCreate: (
      this: IUserModel,
      {
        firstName,
        lastName,
        age,
      }: { firstName: string; lastName: string; age: number }
    ) => Promise<IUserDocument>;
    findByAge: (
      this: IUserModel,
      min?: number,
      max?: number
    ) => Promise<IUserDocument[]>;
}
`

**Comment by hansbeld** [comment]
I was just looking in to your comment above. The project was on the back burner for a while

**Comment by Skitch90** [comment]
> 
> 
> > running into the same problem. If I add a method definition to the IUserDocument interface it will throw the same error.
> 
> UPDATE.
> it seems the inheritance chain needs to be changed to fit the same shape of UserScheme. A more elegant way to solve this problem could be:
> 
> ```
> - export interface IUserModel extends Model<IUserDocument>
> + export interface IUserModel extends Model<Document<IUserDocument>> {
>     findOneOrCreate: (
>       this: IUserModel,
>       {
>         firstName,
>         lastName,
>         age,
>       }: { firstName: string; lastName: string; age: number }
>     ) => Promise<IUserDocument>;
>     findByAge: (
>       this: IUserModel,
>       min?: number,
>       max?: number
>     ) => Promise<IUserDocument[]>;
> }
> ```

Using this approach the initial problem is fixed, but the definition of UserModel now has a compilation error 
![immagine](https://user-images.githubusercontent.com/4163732/129474604-e7399609-4257-4751-91e9-37cc6ca17335.png)

**Comment by BretCameron** [comment]
Hi everyone. I have updated the repo to use TypeScript 4 and edit the static methods to remove the type error.

The way to fix it is by removing the first argument `this`, which is no longer necessary.

So the `users.statics.ts` file should now look like this:

```ts
import { IUserDocument } from "./users.types";

export async function findOneOrCreate({
  firstName,
  lastName,
  age,
}: {
  firstName: string;
  lastName: string;
  age: number;
}) {
  const record = await this.findOne({ firstName, lastName, age });
  if (record) {
    return record;
  } else {
    return this.create({ firstName, lastName, age });
  }
}

export async function findByAge(
  min?: number,
  max?: number
): Promise<IUserDocument[]> {
  return this.find({ age: { $gte: min || 0, $lte: max || Infinity } });
}
```

I'll close this issue for now, but feel free to raise another if you have any problems.
